// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtjgowpauufdhuswtpnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0amdvd3BhdXVmZGh1c3d0cG5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjQ0MDgsImV4cCI6MjA3MTcwMDQwOH0.FnyU0ky2toje1kLlc7O36ju7-7D1r8a_sTVRoTY9BXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});